kind: azks-config
azks:
  name: epiphany
  rg_name: aks_only_tests-rg
  vnet_name: aks_only_tests-vnet
  address_prefix: 10.0.0.0/16
  # default node pool
  size: 3
  min: 2
  max: 5
  vm_size: Standard_DS2_v2
  disk_size: 36
  auto_scaling: true
  rsa_pub_path: "/shared/vms_rsa.pub"
